function createStimulus(stim_type)
{
	// create a div to hold stimulus
	$('body').append($('<div id="stimulus"></div>'));

	// create the raphael object
	var width = 320;
	var height = 200;
	var paper = Raphael("stimulus", width, height);

	var min = 1;
	var max = 20;
	var A = Math.floor(Math.random() * (max - min + 1)) + min;
	var B = Math.floor(Math.random() * (max - min + 1)) + min;
	var C = Math.floor(Math.random() * (max - min + 1)) + min;

	var P1 = Math.floor(Math.random()  * 11);
	var P2 = Math.floor(Math.random()  * 11);

	// get the html string generated by above code
	var html = $('#stimulus').html();

	// remove the stimulus from the html document
	$('#stimulus').remove();

	// return html string
	return html;
}

//In Stimulus Type 1, both probes appear.
if (stim_type == type_1) 
{
	while ((A - B - C) < 0)
	{ 
		A = Math.floor(Math.random() * (max - min + 1)) + min;
		B = Math.floor(Math.random() * (max - min + 1)) + min;
		C = Math.floor(Math.random() * (max - min + 1)) + min;
	}
		var t = paper.text(50, 50, A);
		var u = paper.text(65, 50, "-");
		var v = paper.text(80, 50, B);
		var w = paper.text(95, 50, "-");
		var x = paper.text(110, 50, C);
	
	while (P1 === P2)
	{
		P2 = Math.floor(Math.random() * 11);
	}
		var y = paper.text(65, 40, P1);
		var z = paper.text(95, 40, P2);
}

//In Stimulus Type 2, only the first probe appears.
else if (stim_type == type_2)
{
	while ((A - B - C) < 0)
	{ 
		A = Math.floor(Math.random() * (max - min + 1)) + min;
		B = Math.floor(Math.random() * (max - min + 1)) + min;
		C = Math.floor(Math.random() * (max - min + 1)) + min;
	}
		var t = paper.text(50, 50, A);
		var u = paper.text(65, 50, "-");
		var v = paper.text(80, 50, B);
		var w = paper.text(95, 50, "-");
		var x = paper.text(110, 50, C);
	
	while (P1 === P2)
	{
		P2 = Math.floor(Math.random() * 11);
	}
		var y = paper.text(65, 40, P1);
	}

//In Stimulus Type 3, only the second probe appears.
else if (stim_type == type_3) 
{
	while ((A - B - C) < 0)
	{ 
		A = Math.floor(Math.random() * (max - min + 1)) + min;
		B = Math.floor(Math.random() * (max - min + 1)) + min;
		C = Math.floor(Math.random() * (max - min + 1)) + min;
	}
		var t = paper.text(50, 50, A);
		var u = paper.text(65, 50, "-");
		var v = paper.text(80, 50, B);
		var w = paper.text(95, 50, "-");
		var x = paper.text(110, 50, C);
	
	while (P1 === P2)
	{
		P2 = Math.floor(Math.random() * 11);
	}
		var z = paper.text(95, 40, P2);
}	

//In Stimulus Type 4, no probes appear.
else (stim_type == type_4) 
{
	while ((A - B - C) < 0)
	{ 
		A = Math.floor(Math.random() * (max - min + 1)) + min;
		B = Math.floor(Math.random() * (max - min + 1)) + min;
		C = Math.floor(Math.random() * (max - min + 1)) + min;
	}
		var t = paper.text(50, 50, A);
		var u = paper.text(65, 50, "-");
		var v = paper.text(80, 50, B);
		var w = paper.text(95, 50, "-");
		var x = paper.text(110, 50, C);
